version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    env_file: symfony-api/.env
    depends_on:
      - php
    ports:
      - 8800:80
    volumes:
      - ./symfony-api:/var/www/app:rw
      - ./docker/server/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    tty: true

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - WITH_XDEBUG=true
    env_file: symfony-api/.env
    volumes:
      - ./symfony-api:/var/www/app:rw
    tty: true
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfonyapi
      MYSQL_PASSWORD: symfonyapi

    volumes:
      - symfony_db:/var/lib/mysql:cached # Persist the database in a Docker volume.
    networks:
      - symfony

volumes:
  symfony_db:

networks:
  symfony:
