version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    env_file: .env
    depends_on:
      - php
    ports:
      - 8800:80
    volumes:
      - ./symfony-api:/var/www/app:rw
      - ./docker/server/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    tty: true

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - WITH_XDEBUG=true
    env_file: .env
    volumes:
      - ./symfony-api:/var/www/app:rw
    tty: true
  db:
    image: postgres:11-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: root
    env_file: .env

    volumes:
      - symfony_db:/var/lib/mysql:cached # Persist the database in a Docker volume.
    networks:
      - symfony

volumes:
  symfony_db:

networks:
  symfony:
